spring.application.name=livequiz-backend

# Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/livequiz
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA Config
# Automatically create/update tables based on @Entity classes
spring.jpa.hibernate.ddl-auto=update
# Show SQL queries in logs (good for learning)
spring.jpa.show-sql=true

# Server Config
spring.profiles.active=postgres

## Throw 404 instead of default whitelabel error page
spring.mvc.throw-exception-if-no-handler-found=true
## Disable default static resource handling - used to throw 404 for unknown paths
spring.web.resources.add-mappings=false
