spring.application.name=livequiz-backend

# Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/livequiz
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA Config
# Automatically create/update tables based on @Entity classes
spring.jpa.hibernate.ddl-auto=update
# Show SQL queries in logs (good for learning)
spring.jpa.show-sql=true

# Server Config
spring.profiles.active=postgres
